#!/bin/bash
#
# chkconfig: 345 99 01
# description: app

. /etc/init.d/functions

name="app"
parent_dir="/opt/$name"
pidfile="/var/run/${name}/pid"
lockfile="/var/lock/subsys/$name"
incantation="python $parent_dir/app.py $pidfile >/dev/null 2>&1 &"
user="vagrant"

start() {
  echo -n "Starting $name: "
  daemon --pidfile $pidfile --user $user $incantation
  local retval=$?
  [ $retval -eq 0 ] && touch $lockfile
  return $retval
}

stop() {
  echo -n "Shutting down $name: "
  killproc -p $pidfile $name
  local retval=$?
  [ $retval -eq 0 ] && rm -f $lockfile
  return $retval
}

case "$1" in
  start) start ;;
  stop) stop ;;
  status) status -p $pidfile $name ;;
  restart) stop; start ;;
  *) echo "Usage: $name {start|stop|status|restart}"; exit 1 ;;
esac
exit $?
